// Copyright (c) 2009 - 2020, Uwe Finke. All rights reserved.
// Subject to BSD License. See "license.txt" distributed with this package.

package de.ufinke.cubaja.cafebabe;

import java.io.BufferedOutputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;

/**
 * <p>
 * <code>ClassLoader</code> which loads generated bytecode.
 * A {@link Generator} must be set by {@link #setGenerator} before {@link #findClass} 
 * is called indirectly
 * by {@link java.lang.ClassLoader#loadClass}.
 * </p><p>
 * There may be a system property <code>de.ufinke.cubaja.cafebabe.dump</code> with a
 * path name as its value. If the property exists, the 'loaded' bytecode will be dumped into the given
 * directory.
 * </p><p>
 * Because of the dependencies between <code>setGenerator</code> and
 * <code>findClass</code>, this class is not threadsafe.
 * </p>
 * @author Uwe Finke
 */
public class Loader extends ClassLoader {

  /**
   * <p>
   * Convenience method to generate and load a class.
   * </p><p>
   * Creates a <code>Loader</code> with the <code>ClassLoader</code> of a context class as parent loader
   * and passes the <code>Generator</code> to it.
   * The name of the generated class is <code>'Generated'</code> plus
   * the given <code>nameSuffix</code>es, each separated by an underline character.
   * If a <code>nameSuffix</code> is of type <code>Class</code>, the class name
   * is used as nameSuffix.
   * Dots in a <code>nameSuffix</code> are replaced by underlines.
   * </p>
   * @param contextClass context class
   * @param generator generator
   * @param nameSuffix optional name suffixes to build the name of the generated class
   * @return generated class
   * @throws ClassNotFoundException when the context class could not be found
   */
  public static Class<?> createClass(Class<?> contextClass, Generator generator, Object... nameSuffix) throws ClassNotFoundException {
    
    Loader loader = new Loader(contextClass.getClassLoader());
    loader.setGenerator(generator);
    
    StringBuilder sb = new StringBuilder(200);
    sb.append(generator.getClass().getPackage().getName());
    sb.append(".Generated");
    for (int i = 0; i < nameSuffix.length; i++) {
      sb.append('_');
      Object suffix = nameSuffix[i];
      if (suffix.getClass() == Class.class) {
        Class<?> clazz = (Class<?>) suffix;
        suffix = clazz.getName();
      }
      sb.append(suffix.toString().replace('.', '_'));
    }
    String className = sb.toString();
    
    return loader.loadClass(className);
  }
  
  /**
   * Same as {@link #createClass(Class, Generator, Object...)}, 
   * with the <code>generator</code>s <code>ClassLoader</code> as parent loader.
   * @param generator generator
   * @param nameSuffix optional name suffixes to build the name of the generated class
   * @return generated class
   * @throws ClassNotFoundException when the context class could not be found
   */
  public static Class<?> createClass(Generator generator, Object... nameSuffix) throws ClassNotFoundException {
  	
  	return createClass(generator.getClass(), generator, nameSuffix);
  }
  
  private Generator generator;
  
  /**
   * Default constructor.
   * Parent class loader is the system class loader.
   */
  public Loader() {
    
  }
  
  /**
   * Constructor with explicit parent class loader.
   * @param parentLoader parent class loader
   */
  public Loader(ClassLoader parentLoader) {
    
    super(parentLoader);
  }
  
  /**
   * Sets the generator.
   * @param generator the generator
   */
  public void setGenerator(Generator generator) {
    
    this.generator = generator;
  }
  
  /**
   * Calls the generator and defines the <code>Class</code>.
   * @param className name of class to find
   */
  protected Class<?> findClass(String className) throws ClassNotFoundException {
    
    try {
      return doFindClass(className);
    } catch (Throwable t) {
      throw new ClassNotFoundException(className, t);
    }
  }
  
  private Class<?> doFindClass(String className) throws Exception {
    
    GenClass genClass = generator.generate(className);
    
    ByteArrayOutputStream buffer = new ByteArrayOutputStream();
    DataOutputStream out = new DataOutputStream(buffer);
    genClass.generate(out);
    out.close();
    byte[] array = buffer.toByteArray();
    
    dump(className, array);
    
    Class<?> clazz = defineClass(className, array, 0, array.length);
    resolveClass(clazz);
    
    return clazz;
  }
  
  private void dump(String className, byte[] array) throws Exception {
    
    String dumpDirectory = System.getProperty(Loader.class.getPackage().getName() + ".dump");
    if (dumpDirectory == null) {
      return;
    }
    
    File classFile = new File(className.replace('.', '/'));
    String parent = classFile.getParent();
    String dirName = (parent == null) ? dumpDirectory : dumpDirectory + "/" + parent;
    File dir = new File(dirName);
    dir.mkdirs();
    File file = new File(dir, classFile.getName() + ".class");
    
    BufferedOutputStream stream = new BufferedOutputStream(new FileOutputStream(file));
    stream.write(array);
    stream.close();
  }
}
